const MASTER_BANK = [
   
{ q: "कंप्यूटर में Input और Output को नियंत्रित करने वाला भाग कौन सा है?", options: ["Control Unit", "ALU", "Memory Unit", "Cache"], answer: 0, topic: "Computer Basics" },
  { q: "Multithreading किससे संबंधित है?", options: ["Multiple Users", "Multiple Tasks within a Program", "Multiple Computers", "Multiple Printers"], answer: 1, topic: "OS" },
  { q: "LibreOffice Writer में Find & Replace की शॉर्टकट कुंजी क्या है?", options: ["Ctrl + R", "Ctrl + H", "Ctrl + F7", "Ctrl + F9"], answer: 1, topic: "Writer" },
  { q: "LibreOffice Calc में Freeze Panes का उपयोग किसलिए होता है?", options: ["Column/Row को Fix करना", "Cell Lock करना", "Password लगाना", "Data Hide करना"], answer: 0, topic: "Calc" },
  { q: "Impress में Custom Animation का प्रयोग कहाँ होता है?", options: ["Slide Layout बदलने में", "Text & Object Effects देने में", "Slide Transition बदलने में", "Table बनाने में"], answer: 1, topic: "Impress" },
  { q: "Internet में ISP का फुल फॉर्म क्या है?", options: ["Internet Service Provider", "Internal System Protocol", "International Service Point", "Integrated Service Program"], answer: 0, topic: "Internet" },
  { q: "Gmail में Draft का क्या अर्थ है?", options: ["Sent Message", "Deleted Message", "Unsent Saved Message", "Spam Mail"], answer: 2, topic: "Email" },
  { q: "AEPS का फुल फॉर्म क्या है?", options: ["Aadhaar Enabled Payment System", "Automated Easy Payment Service", "Aadhaar Electronic Payment Software", "Aadhaar E-Process System"], answer: 0, topic: "Banking" },
  { q: "Cyber Crime में DoS का फुल फॉर्म क्या है?", options: ["Denial of Service", "Data on Server", "Disk Operating System", "Direct Online Service"], answer: 0, topic: "Cyber Security" },
  { q: "AI में Chatbot का उपयोग किस लिए किया जाता है?", options: ["Data Storage", "Customer Interaction Automation", "Computer Programming", "System Booting"], answer: 1, topic: "AI" },
  { q: "कंप्यूटर की गति को किससे मापा जाता है?", options: ["Gigahertz (GHz)", "Megabyte (MB)", "Gigabyte (GB)", "Megapixel (MP)"], answer: 0, topic: "Computer Basics" },
  { q: "Batch Operating System किस प्रकार का होता है?", options: ["Real Time OS", "Multi User OS", "Single Tasking OS", "Offline Processing OS"], answer: 3, topic: "OS" },
  { q: "LibreOffice Writer में Word Count देखने की शॉर्टकट कुंजी है:", options: ["Ctrl + W", "Ctrl + Shift + C", "Ctrl + F12", "Ctrl + Shift + G"], answer: 3, topic: "Writer" },
  { q: "Calc में Cell Comment Insert करने की शॉर्टकट कुंजी क्या है?", options: ["Ctrl + Alt + C", "Ctrl + Shift + C", "Alt + C", "Ctrl + C"], answer: 0, topic: "Calc" },
  { q: "Impress में Handout View किसलिए होता है?", options: ["Presentation Edit करना", "Print Layout View करना", "Slide Show Start करना", "Animation Add करना"], answer: 1, topic: "Impress" },
  { q: "Internet का आविष्कार किसने किया?", options: ["Tim Berners-Lee", "Vint Cerf & Robert Kahn", "Bill Gates", "Steve Jobs"], answer: 1, topic: "Internet" },
  { q: "ई-मेल का पासवर्ड सुरक्षित रखने का सही तरीका कौन सा है?", options: ["Strong Password बनाना", "Password Share करना", "Simple Password रखना", "Same Password हर जगह रखना"], answer: 0, topic: "Cyber Security" },
  { q: "RTGS का फुल फॉर्म क्या है?", options: ["Real Time Gross Settlement", "Real Transfer General System", "Rapid Transfer Gateway System", "Real Transaction General Service"], answer: 0, topic: "Banking" },
  { q: "Cyber Security में Encryption का मतलब क्या है?", options: ["Data Hide करना", "Data को Secure Code में Convert करना", "Data Delete करना", "Data Backup करना"], answer: 1, topic: "Cyber Security" },
  { q: "AI में Deep Learning का आधार क्या है?", options: ["Neural Networks", "Data Tables", "Simple Programs", "Spreadsheets"], answer: 0, topic: "AI" },
  { q: "Secondary Storage Device का उदाहरण कौन सा है?", options: ["RAM", "Hard Disk", "Cache", "Register"], answer: 1, topic: "Hardware" },
  { q: "GUI आधारित पहला Operating System कौन सा था?", options: ["UNIX", "Windows 95", "Mac OS", "MS-DOS"], answer: 2, topic: "OS" },
  { q: "LibreOffice Writer में Page Break डालने की शॉर्टकट कुंजी क्या है?", options: ["Ctrl + Enter", "Ctrl + Shift + Enter", "Alt + Enter", "Shift + Enter"], answer: 0, topic: "Writer" },
  { q: "Calc में MAX Function का प्रयोग किसके लिए होता है?", options: ["Minimum Value निकालने के लिए", "Highest Value निकालने के लिए", "Average Value निकालने के लिए", "Sum निकालने के लिए"], answer: 1, topic: "Calc" },
  { q: "Impress में Slide Show को End करने की शॉर्टकट कुंजी क्या है?", options: ["Esc", "End", "Ctrl + Q", "Shift + Esc"], answer: 0, topic: "Impress" },
  { q: "URL में 'https' का क्या अर्थ है?", options: ["Hyper Transfer Text Standard", "Hyper Text Transfer Secure", "Hyperlink Text Secure", "High Transfer Protocol System"], answer: 1, topic: "Internet" },
  { q: "WhatsApp किस प्रकार की Application है?", options: ["Social Media App", "Messaging App", "Video Sharing App", "Search Engine"], answer: 1, topic: "Social" },
  { q: "NPCI का पूरा नाम क्या है?", options: ["National Payment Corporation of India", "National Pay Card India", "New Payment Control of India", "National Processing Center of India"], answer: 0, topic: "Banking" },
  { q: "Cyber Security में CAPTCHA का उपयोग किसलिए होता है?", options: ["Virus Detect करने के लिए", "Human और Bot को अलग करने के लिए", "Password Reset करने के लिए", "Data Backup करने के लिए"], answer: 1, topic: "Cyber Security" },
  { q: "AI में Speech Recognition किस काम आता है?", options: ["Text Formatting", "Human Voice को समझना", "Computer Programming", "Image Creation"], answer: 1, topic: "AI" },
  { q: "Computer के सबसे छोटे तेज़ Memory Unit को क्या कहते हैं?", options: ["RAM", "Cache", "Register", "Hard Disk"], answer: 2, topic: "Hardware" },
  { q: "Linux किस प्रकार का Operating System है?", options: ["Proprietary", "Open Source", "Paid Only", "Mobile Only"], answer: 1, topic: "OS" },
  { q: "LibreOffice Writer में Superscript का शॉर्टकट क्या है?", options: ["Ctrl + =", "Ctrl + Shift + P", "Ctrl + Shift + +", "Alt + P"], answer: 2, topic: "Writer" },
  { q: "Calc में SUM Function का प्रयोग किस लिए होता है?", options: ["Multiply Values", "Add Values", "Divide Values", "Average Values"], answer: 1, topic: "Calc" },
  { q: "Impress में Notes Pane का उपयोग किसलिए होता है?", options: ["Slide Order Change करना", "Speaker Notes Add करना", "Background Design Change करना", "Transition Control करना"], answer: 1, topic: "Impress" },
  { q: "Modem का मुख्य कार्य क्या है?", options: ["Data Encrypt करना", "Digital ↔ Analog Signal Convert करना", "Virus Detect करना", "Backup लेना"], answer: 1, topic: "Networking" },
  { q: "Instagram किस प्रकार का Platform है?", options: ["Video Streaming Site", "Photo & Video Sharing App", "Professional Networking Site", "News Portal"], answer: 1, topic: "Social" },
  { q: "Net Banking को और किस नाम से जाना जाता है?", options: ["Online Banking", "Digital Payment", "Mobile Payment", "Direct Transfer"], answer: 0, topic: "Banking" },
  { q: "Cyber Security में Two-Factor Authentication का उपयोग क्यों किया जाता है?", options: ["Fast Login के लिए", "Extra Security Layer Provide करने के लिए", "Data Compress करने के लिए", "File Share करने के लिए"], answer: 1, topic: "Cyber Security" },
  { q: "AI में Turing Test का उपयोग किस लिए किया जाता है?", options: ["Computer Memory मापने के लिए", "Computer Speed चेक करने के लिए", "Machine Intelligence मापने के लिए", "Computer Programming करने के लिए"], answer: 2, topic: "AI" },
   { q: "निम्नलिखित में से कौन हार्डवेयर का उदाहरण है?", options: ["MS Word", "Mouse", "Windows", "Antivirus"], answer: 1, topic: "कंप्यूटर बेसिक" },
  { q: "कंप्यूटर का मस्तिष्क कहलाता है —", options: ["मॉनिटर", "CPU", "RAM", "कीबोर्ड"], answer: 1, topic: "कंप्यूटर बेसिक" },
  { q: "ऑपरेटिंग सिस्टम किस प्रकार का सॉफ़्टवेयर है?", options: ["एप्लिकेशन सॉफ्टवेयर", "सिस्टम सॉफ्टवेयर", "यूटिलिटी सॉफ्टवेयर", "कस्टम सॉफ्टवेयर"], answer: 1, topic: "सॉफ्टवेयर" },
  { q: "कर्सर के दाईं ओर के टेक्स्ट को हटाने के लिए कौन-सी कुंजी प्रयोग की जाती है?", options: ["Backspace", "Delete", "Shift", "Ctrl"], answer: 1, topic: "कीबोर्ड" },
  { q: "LibreOffice Writer की फ़ाइल किस एक्सटेंशन में सेव होती है?", options: [".xls", ".odt", ".odp", ".ods"], answer: 1, topic: "Writer" },
  { q: "LibreOffice Writer में कॉपी करने की शॉर्टकट कुंजी है —", options: ["Ctrl + C", "Ctrl + X", "Ctrl + V", "Ctrl + P"], answer: 0, topic: "Writer" },
  { q: "LibreOffice Calc में rows को किससे पहचाना जाता है?", options: ["नंबर", "अक्षर", "सिंबल", "रंग"], answer: 0, topic: "Calc" },
  { q: "Calc में योग (Sum) निकालने के लिए कौन-सा फंक्शन प्रयोग होता है?", options: ["=ADD()", "=SUM()", "=TOTAL()", "=PLUS()"], answer: 1, topic: "Calc" },
  { q: "LibreOffice Impress में नई स्लाइड कैसे जोड़ी जाती है?", options: ["Insert → Page", "Insert → Slide", "File → New", "Format → Slide"], answer: 1, topic: "Impress" },
  { q: "WWW का पूर्ण रूप क्या है?", options: ["World Wide Web", "World Wide Word", "Wide Web World", "Web World Wide"], answer: 0, topic: "Internet" },
  { q: "URL का पूर्ण रूप है —", options: ["Universal Resource Locator", "Uniform Resource Locator", "Unique Resource Link", "User Related Locator"], answer: 1, topic: "Internet" },
  { q: "निम्नलिखित में से कौन सर्च इंजन का उदाहरण है?", options: ["Gmail", "Yahoo", "WhatsApp", "Facebook"], answer: 1, topic: "Internet" },
  { q: "ईमेल ट्रांसमिशन के लिए कौन-सा प्रोटोकॉल प्रयोग होता है?", options: ["FTP", "SMTP", "HTTP", "IP"], answer: 1, topic: "नेटवर्किंग" },
  { q: "निम्नलिखित में से कौन-सी सोशल नेटवर्किंग साइट है?", options: ["Amazon", "Facebook", "Flipkart", "eBay"], answer: 1, topic: "Social" },
  { q: "ई-गवर्नेंस क्या है?", options: ["ऑनलाइन शॉपिंग", "ऑनलाइन डिलीवरी", "इलेक्ट्रॉनिक गवर्नेंस", "कंप्यूटर गेम्स"], answer: 2, topic: "सरकारी योजना" },
  { q: "निम्नलिखित में से कौन-सा डिजिटल पेमेंट ऐप है?", options: ["Paytm", "VLC", "Photoshop", "Notepad++"], answer: 0, topic: "Banking" },
  { q: "UPI का पूर्ण रूप क्या है?", options: ["Unified Payment Interface", "Universal Payment Integration", "User Payment Internet", "Unique Pay Interface"], answer: 0, topic: "Banking" },
  { q: "निम्नलिखित में से कौन डिजिटल वित्तीय उपकरण नहीं है?", options: ["BHIM", "Google Pay", "Cash", "PhonePe"], answer: 2, topic: "Banking" },
  { q: "ATM का पूर्ण रूप क्या है?", options: ["Automated Teller Machine", "Auto Transaction Machine", "Automatic Teller Module", "उपरोक्त में से कोई नहीं"], answer: 0, topic: "Banking" },
  { q: "निम्नलिखित में से कौन साइबर हमले का प्रकार है?", options: ["Phishing", "Printing", "Browsing", "Typing"], answer: 0, topic: "Cyber Security" },
  { q: "मजबूत पासवर्ड में क्या शामिल होना चाहिए?", options: ["केवल अक्षर", "अक्षर, अंक और चिन्ह", "केवल अंक", "केवल नाम"], answer: 1, topic: "Cyber Security" },
  { q: "एंटीवायरस सॉफ्टवेयर का प्रयोग किया जाता है —", options: ["फाइल डिलीट करने के लिए", "वायरस को पहचानने और हटाने के लिए", "ऑपरेटिंग सिस्टम इंस्टॉल करने के लिए", "डॉक्युमेंट लिखने के लिए"], answer: 1, topic: "Security" },
  { q: "निम्नलिखित में से कौन ऑपरेटिंग सिस्टम का उदाहरण नहीं है?", options: ["Linux", "Windows", "MS Excel", "macOS"], answer: 2, topic: "OS" },
  { q: "फ़ाइल एक्सप्लोरर का उपयोग किया जाता है —", options: ["ईमेल लिखने के लिए", "फाइल और फोल्डर प्रबंधन के लिए", "वीडियो एडिट करने के लिए", "गेम खेलने के लिए"], answer: 1, topic: "Software" },
  { q: "कंप्यूटर में डाटा की सबसे छोटी इकाई है —", options: ["Byte", "Bit", "KB", "MB"], answer: 1, topic: "कंप्यूटर बेसिक" },
  { q: "Calc में हर formula के पहले कौन-सा symbol आता है?", options: ["+", "=", "#", "$"], answer: 1, topic: "Calc" },
  { q: "कंप्यूटर को शुरू करने की प्रक्रिया कहलाती है —", options: ["Booting", "Loading", "Saving", "Formatting"], answer: 0, topic: "कंप्यूटर बेसिक" },
  { q: "क्लाउड स्टोरेज का मतलब है —", options: ["ऑनलाइन डेटा स्टोरेज", "लोकल डिस्क स्टोरेज", "पेन ड्राइव", "हार्ड डिस्क"], answer: 0, topic: "Internet" },
  { q: "ऑनलाइन वीडियो मीटिंग के लिए कौन-सा ऐप प्रयोग होता है?", options: ["Zoom", "VLC", "WinRAR", "MS Paint"], answer: 0, topic: "Software" },
  { q: "LibreOffice Calc किसके समान है?", options: ["MS Word", "MS Excel", "PowerPoint", "Outlook"], answer: 1, topic: "Calc" },
  { q: "टेक्स्ट पेस्ट करने के लिए कौन-सी कुंजी प्रयोग की जाती है?", options: ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], answer: 1, topic: "कीबोर्ड" },
  { q: "Impress में Slide Show शुरू करने के लिए कौन-सी कुंजी प्रयोग होती है?", options: ["F5", "F2", "F10", "F12"], answer: 0, topic: "Impress" },
  { q: "निम्नलिखित में से कौन-सा एक AI एप्लिकेशन है?", options: ["ChatGPT", "Notepad", "Calculator", "VLC"], answer: 0, topic: "AI" },
  { q: "रोबोटिक्स किसका उदाहरण है?", options: ["AI और Automation", "वर्ड प्रोसेसिंग", "स्प्रेडशीट", "साइबर क्राइम"], answer: 0, topic: "AI" },
  { q: "कंप्यूटर का घटक नहीं है —", options: ["Input", "Output", "Compiler", "Processing"], answer: 2, topic: "कंप्यूटर बेसिक" },
  { q: "Gmail किसका उदाहरण है?", options: ["ईमेल सेवा", "सोशल मीडिया", "सर्च इंजन", "फाइल मैनेजर"], answer: 0, topic: "Internet" },
  { q: "निम्नलिखित में से कौन प्रस्तुति (Presentation) के लिए प्रयोग होता है?", options: ["LibreOffice Impress", "LibreOffice Writer", "LibreOffice Calc", "MS Paint"], answer: 0, topic: "Impress" },
  { q: "डाटा को मशीन-पठनीय रूप में बदलने वाला उपकरण है —", options: ["इनपुट डिवाइस", "आउटपुट डिवाइस", "स्टोरेज डिवाइस", "प्रोसेसिंग डिवाइस"], answer: 0, topic: "Hardware" },
  { q: "PDF का पूर्ण रूप क्या है?", options: ["Portable Document Format", "Program Data File", "Printed Data File", "उपरोक्त में से कोई नहीं"], answer: 0, topic: "Documents" },
  { q: "AI का पूर्ण रूप है —", options: ["Artificial Intelligence", "Automated Information", "Advanced Integration", "Application Interface"], answer: 0, topic: "AI" },
   { q: "LibreOffice Writer में Header और Footer जोड़ने का विकल्प कहाँ मिलता है?", options: ["File > Insert", "View > Header and Footer", "Insert > Header and Footer", "Format > Page"], answer: 2, topic: "Writer" },
  { q: "NEFT का पूर्ण रूप क्या है?", options: ["National Exchange for Funds Transfer", "National Electronic Funds Transfer", "New Easy Funds Transfer", "National Essential Funds Transfer"], answer: 1, topic: "Banking" },
  { q: "LibreOffice Calc में =NOW() function का क्या कार्य है?", options: ["वर्तमान समय दिखाना", "वर्तमान दिनांक और समय दिखाना", "सिर्फ दिनांक दिखाना", "महीने का नाम दिखाना"], answer: 1, topic: "Calc" },
  { q: "“Phishing” किससे संबंधित है?", options: ["प्रोग्रामिंग", "ईमेल धोखाधड़ी", "वीडियो एडिटिंग", "ऑडियो कम्प्रेशन"], answer: 1, topic: "Cyber Security" },
  { q: "LibreOffice Impress में Slide Show शुरू करने की शॉर्टकट कुंजी क्या है?", options: ["Ctrl + S", "Shift + F5", "F5", "Ctrl + F5"], answer: 2, topic: "Impress" },
  { q: "IFSC कोड का प्रयोग कहाँ किया जाता है?", options: ["बीमा भरने में", "बैंक लेनदेन में", "आधार सत्यापन में", "PAN आवेदन में"], answer: 1, topic: "Banking" },
  { q: "LibreOffice Writer में Page Orientation बदलने के लिए कौन-सा मेनू प्रयोग होता है?", options: ["File", "View", "Format", "Page Style"], answer: 3, topic: "Writer" },
  { q: "कंप्यूटर में F1 कुंजी का सामान्य उपयोग क्या है?", options: ["Save", "Undo", "Help", "Rename"], answer: 2, topic: "Keyboard" },
  { q: "WhatsApp में end-to-end encryption का क्या अर्थ है?", options: ["संदेश एन्क्रिप्ट होकर जाता है और केवल रिसीवर ही उसे डिक्रिप्ट कर सकता है", "संदेश सादा टेक्स्ट में भेजा जाता है", "संदेश केवल एक बार खोला जा सकता है", "चैट हिस्ट्री अपने आप डिलीट हो जाती है"], answer: 0, topic: "Cyber Security" },
  { q: "LibreOffice Calc में कौन-सा फ़ंक्शन सबसे बड़ा मान देता है?", options: ["=MIN()", "=LARGE()", "=MAX()", "=BIG()"], answer: 2, topic: "Calc" },
  { q: "Windows OS में Recycle Bin में डिलीट की गई फ़ाइल कब तक रहती है?", options: ["1 दिन", "जब तक मैन्युअली डिलीट न करें", "30 दिन", "1 सप्ताह"], answer: 1, topic: "Windows" },
   { q: "LibreOffice Writer में शब्दों की वर्तनी (Spelling) जाँचने की शॉर्टकट कुंजी क्या है?", options: ["F7", "Ctrl + F7", "Alt + F7", "Shift + F7"], answer: 0, topic: "Writer" },
  { q: "LibreOffice Calc में औसत (Average) निकालने का फ़ंक्शन कौन-सा है?", options: ["=MEAN()", "=AVERAGE()", "=MID()", "=AVG()"], answer: 1, topic: "Calc" },
  { q: "PDF फाइल को खोलने के लिए सामान्यतः कौन-सा एप्लिकेशन प्रयोग होता है?", options: ["MS Word", "Adobe Reader", "Paint", "Notepad"], answer: 1, topic: "Documents" },
  { q: "कंप्यूटर की अस्थायी मेमोरी कौन सी है?", options: ["ROM", "RAM", "Hard Disk", "CD-ROM"], answer: 1, topic: "Hardware" },
  { q: "LibreOffice Impress में Slide Transition कहाँ से लगाई जाती है?", options: ["Insert मेनू से", "Format मेनू से", "Slide मेनू से", "Transitions पैनल से"], answer: 3, topic: "Impress" },
  { q: "कंप्यूटर वायरस क्या है?", options: ["हार्डवेयर उपकरण", "दुर्भावनापूर्ण प्रोग्राम", "एंटीवायरस का हिस्सा", "इनपुट डिवाइस"], answer: 1, topic: "Cyber Security" },
  { q: "HTTP का पूर्ण रूप क्या है?", options: ["Hyper Text Transfer Protocol", "High Transfer Type Protocol", "Hyperlink Text Transfer Program", "Host Transfer Test Process"], answer: 0, topic: "Internet" },
  { q: "LibreOffice Calc में सेल एडिट करने की शॉर्टकट कुंजी है —", options: ["F1", "F2", "F3", "F4"], answer: 1, topic: "Calc" },
  { q: "Windows में Run डायलॉग बॉक्स खोलने की शॉर्टकट कुंजी क्या है?", options: ["Ctrl + R", "Win + R", "Alt + R", "Shift + R"], answer: 1, topic: "Windows" },
  { q: "CPU का कौन सा भाग गणना करता है?", options: ["Control Unit", "Arithmetic Logic Unit (ALU)", "Memory Unit", "Register"], answer: 1, topic: "Hardware" },
  { q: "Cyber Security में Firewall का उपयोग किस लिए किया जाता है?", options: ["नेटवर्क सुरक्षा के लिए", "डेटा बैकअप के लिए", "वायरस हटाने के लिए", "स्पीड बढ़ाने के लिए"], answer: 0, topic: "Cyber Security" },
  { q: "कंप्यूटर का फुल फॉर्म क्या है?", options: ["Commonly Operated Machine Used for Technical and Educational Research", "Compute Unit for Research", "Computerized Unit for Testing", "None"], answer: 0, topic: "Basics" },
  { q: "Bluetooth तकनीक का उपयोग कहाँ होता है?", options: ["केवल इंटरनेट के लिए", "वायरलेस डेटा ट्रांसफर के लिए", "केवल ऑडियो रिकॉर्डिंग के लिए", "मोबाइल चार्जिंग के लिए"], answer: 1, topic: "Technology" },
  { q: "LibreOffice Writer में लाइन स्पेसिंग बदलने का विकल्प कहाँ होता है?", options: ["Insert", "Format", "Tools", "View"], answer: 1, topic: "Writer" },
  { q: "QR Code का उपयोग किसलिए होता है?", options: ["ऑनलाइन टिकट बुकिंग के लिए", "डेटा को जल्दी पढ़ने के लिए", "नेटवर्क बनाने के लिए", "फाइल सेव करने के लिए"], answer: 1, topic: "Technology" },
  { q: "AI का एक उदाहरण कौन है?", options: ["Google Assistant", "MS Paint", "Notepad", "Calculator"], answer: 0, topic: "AI" },
  { q: "कंप्यूटर नेटवर्क में Modem का कार्य क्या है?", options: ["डाटा एन्क्रिप्ट करना", "Digital और Analog सिग्नल को बदलना", "ऑडियो चलाना", "फाइल सेव करना"], answer: 1, topic: "Networking" },
  { q: "LibreOffice Calc में AutoSum बटन का उपयोग किसलिए होता है?", options: ["संख्या जोड़ने के लिए", "फॉर्मूला एडिट करने के लिए", "चार्ट बनाने के लिए", "सेल लॉक करने के लिए"], answer: 0, topic: "Calc" },
  { q: "कंप्यूटर में BIOS का कार्य क्या है?", options: ["ऑपरेटिंग सिस्टम को लोड करना", "प्रिंटिंग", "फोटो एडिटिंग", "ईमेल भेजना"], answer: 0, topic: "Hardware" },
  { q: "Digital Signature का उपयोग कहाँ होता है?", options: ["ईमेल भेजने में", "ऑनलाइन दस्तावेजों को सत्यापित करने में", "वीडियो डाउनलोड करने में", "गेम खेलने में"], answer: 1, topic: "Cyber Security" }// Note: Strikethrough is through the middle, Overline is above.
];
