const MASTER_BANK = [
   
{ q: "MICR का पूरा नाम क्या है?", options: ["Magnetic Ink Code Reader", "Magnetic Ink Case Reader", "Magnetic Ink Character Recognition", "None"], answer: 2, topic: 'Banking' },
    { q: "IFSC कोड में कितने अंक होते हैं?", options: ["10", "11", "12", "9"], answer: 1, topic: 'Banking' },
    { q: "आधार कार्ड (Aadhar Card) में कितने अंक होते हैं?", options: ["10", "14", "16", "12"], answer: 3, topic: 'Govt' },
    { q: "PAN कार्ड में कितने अंक/अक्षर होते हैं?", options: ["10", "12", "8", "11"], answer: 0, topic: 'Govt' },
    { q: "LibreOffice Calc में अंतिम सेल का एड्रेस क्या होता है?", options: ["XFD1048576", "AMJ1048576", "AMJ65536", "LastCell"], answer: 1, topic: 'Calc' },
    { q: "LibreOffice Writer में डिफॉल्ट फॉन्ट साइज क्या होता है?", options: ["11", "10", "12", "14"], answer: 2, topic: 'Writer' },
    { q: "Twitter का नया नाम क्या है?", options: ["Tweets", "X", "Y", "Meta"], answer: 1, topic: 'Social' },
    { q: "Facebook का मालिक कौन है?", options: ["Elon Musk", "Bill Gates", "Mark Zuckerberg", "Sundar Pichai"], answer: 2, topic: 'Social' },
    { q: "Instagram किसका हिस्सा है?", options: ["Google", "Meta (Facebook)", "Microsoft", "Twitter"], answer: 1, topic: 'Social' },
    { q: "WhatsApp पर अधिकतम कितने लोगों का ग्रुप बना सकते हैं?", options: ["256", "512", "1024", "Unlimited"], answer: 2, topic: 'Social' },
    { q: "LibreOffice Calc में फार्मूला किस सिंबल से शुरू होता है?", options: ["+", "=", "-", "@"], answer: 1, topic: 'Calc' },
    { q: "IPv4 एड्रेस कितने बिट का होता है?", options: ["64 बिट", "128 बिट", "16 बिट", "32 बिट"], answer: 3, topic: 'Internet' },
    { q: "IPv6 एड्रेस कितने बिट का होता है?", options: ["32 बिट", "128 बिट", "64 बिट", "256 बिट"], answer: 1, topic: 'Internet' },
    { q: "पहला वेब ब्राउज़र कौन सा था?", options: ["Mosaic", "Internet Explorer", "WorldWideWeb (Nexus)", "Chrome"], answer: 2, topic: 'Internet' },
    { q: "भारत में इंटरनेट की शुरुआत कब हुई?", options: ["26 जनवरी 1995", "15 अगस्त 1995", "15 अगस्त 1990", "1 जनवरी 2000"], answer: 1, topic: 'Internet' },
    { q: "KYC का पूरा नाम क्या है?", options: ["Know Your Client", "Know Your Cash", "None", "Know Your Customer"], answer: 3, topic: 'Banking' },
    { q: "ATM का पूरा नाम क्या है?", options: ["Any Time Money", "Automated Teller Machine", "All Time Money", "Auto Truck Machine"], answer: 1, topic: 'Banking' },
    { q: "OSS का पूरा नाम क्या है?", options: ["Operating System Software", "Open System Service", "Open Source Software", "None"], answer: 2, topic: 'Fundamentals' },
    { q: "LibreOffice Impress में अधिकतम जूम कितना हो सकता है?", options: ["400%", "3000%", "500%", "600%"], answer: 1, topic: 'Impress' },
    { q: "LibreOffice Writer में अधिकतम जूम कितना हो सकता है?", options: ["500%", "400%", "300%", "600%"], answer: 3, topic: 'Writer' },
    { q: "QR कोड किस प्रकार का कोड है?", options: ["1D", "2D", "3D", "Text"], answer: 1, topic: 'Payments' },
    { q: "BHIM ऐप किसके द्वारा विकसित किया गया?", options: ["RBI", "NPCI", "SBI", "Government"], answer: 1, topic: 'Payments' },
    { q: "NPCI का पूरा नाम क्या है?", options: ["National Payment Company of India", "National Payments Corporation of India", "Non-Payment Corp of India", "None"], answer: 1, topic: 'Payments' },
    { q: "RPA का पूरा नाम क्या है?", options: ["Robot Process Auto", "Robotic Process Automation", "Rapid Process Action", "Real Process Automation"], answer: 1, topic: 'Future' },
    { q: "Big Data क्या है?", options: ["बड़ी फाइल", "बड़ी मात्रा में डेटा जिसे प्रोसेस करना कठिन है", "बड़ा कंप्यूटर", "बड़ा सर्वर"], answer: 1, topic: 'Future' },
    { q: "Blockchain तकनीक का उपयोग किसमें होता है?", options: ["Gaming", "Video Editing", "Cryptocurrency (Bitcoin)", "Music"], answer: 2, topic: 'Future' },
    { q: "3D प्रिंटिंग क्या है?", options: ["कागज पर प्रिंट करना", "फोटो खींचना", "डिजिटल मॉडल से भौतिक वस्तु बनाना", "स्कैन करना"], answer: 2, topic: 'Future' },
    { q: "LibreOffice Calc में आज की तारीख डालने का शॉर्टकट क्या है?", options: ["Ctrl + Shift + ;", "Alt + ;", "Ctrl + ;", "Ctrl + D"], answer: 2, topic: 'Calc' },
    { q: "LibreOffice Calc में अभी का समय डालने का शॉर्टकट क्या है?", options: ["Ctrl + ;", "Alt + Time", "Ctrl + Shift + ;", "Shift + T"], answer: 2, topic: 'Calc' },
    { q: "Computer को रीस्टार्ट करने को क्या कहते हैं?", options: ["Cold Booting", "Warm Booting", "Shut Down", "Logging Off"], answer: 1, topic: 'Fundamentals' },

    // --- MASTER_BANK (Randomized) ---
    { q: "EEPROM का पूरा नाम क्या है?", options: ["Electronic Erasable Programmable Read Only Memory", "Electrically Erasable Programmable Read Only Memory", "Electrically Easy Programmable Read Only Memory", "Easy Erasable Programmable Read Only Memory"], answer: 1, topic: 'Fundamentals' },
    { q: "Email का पूरा नाम क्या है?", options: ["Easy Mail", "Electric Mail", "Electronic Mail", "Engine Mail"], answer: 2, topic: 'Internet' },
    { q: "GPS का पूरा नाम क्या है?", options: ["General Positioning System", "Global Pointing System", "Global Positioning System", "General Pointing System"], answer: 2, topic: 'Internet' },
    { q: "GARV का पूरा नाम क्या है?", options: ["General Vidyutikaran", "Grameen Village", "Grameen Vidyutikaran", "Global Village"], answer: 2, topic: 'Govt' },

    // --- IMAGE_BANK (Randomized) ---
    { q: "एक कॉपीराइट सिंबल बनाने के लिए आप कौन-सी शॉर्टकट 'की' दबाते हैं?", options: ["Ctrl + C", "Alt + C", "Ctrl + Shift + C", "Alt + Ctrl + C"], answer: 3, topic: 'Shortcuts' },
    { q: "निम्नलिखित में से कौन-सा एक वैध विंडोज डेस्कटॉप पेन नहीं है?", options: ["टास्क बार", "क्विक लॉन्च टूलबार", "मेनू बार", "सिस्टम ट्रे"], answer: 2, topic: 'OS' },
    { q: "आईसी चिप में किस धातु का प्रयोग किया जाता है?", options: ["क्रोमियम", "सिलिकॉन", "चाँदी", "निकेल"], answer: 1, topic: 'Fundamentals' },
    { q: "किसी पैराग्राफ पर एक साथ तीन क्लिक करने से सेलेक्ट होगा", options: ["पैराग्राफ का पहला शब्द", "पूरा पैराग्राफ", "पैराग्राफ का पहला वाक्य", "पैराग्राफ का अन्तिम वाक्य"], answer: 1, topic: 'Writer' },
    { q: "'Telenet' एक एप्लीकेशन लेयर प्रोटोकॉल है, जिसका अर्थ है", options: ["टेलीफोन नेटवर्क", "टेलीकनेक्ट नेटवर्क", "टेलीटाइप नेटवर्क", "टेलीविजन नेटवर्क"], answer: 2, topic: 'Network' },
    { q: "प्रत्येक कम्प्यूटर के सभी हिस्सों के ठीक से काम करने और सभी प्रोग्रामों के चलने के लिए उसमें एक _______ होना आवश्यक है।", options: ["कम्पाइलर", "ऑपरेटिंग सिस्टम", "इन्टरप्रेटर", "यूटिलिटी सॉफ्टवेयर"], answer: 1, topic: 'OS' },
    { q: "न्यू डॉक्यूमेंट को ओपन करने के लिए शॉर्टकट 'की' है", options: ["Ctrl + M", "Alt + N", "Alt + Ctrl + N", "None of these"], answer: 3, topic: 'Shortcuts' },
    { q: "Ctrl + X से सेलेक्टेड टेक्स्ट को _______ किया जाता है।", options: ["कॉपी", "कट", "पेस्ट", "डिलीट"], answer: 1, topic: 'Shortcuts' },
    { q: "विण्डोज शटडाउन विकल्प पॉप-अप करने की शॉर्टकट 'की' है", options: ["Ctrl + F4", "Alt + F4", "Ctrl + Shift + F4", "Win + F4"], answer: 1, topic: 'OS' },
    { q: "वह कौन-सा कम्प्यूटर प्रोग्राम है जो कम्प्यूटर उपयोग में न होने की स्थिति में स्क्रीन को ब्लैंक कर देता है या गतिशील छवियों या पैटर्न से भर देता है?", options: ["इमेज स्कैनर", "स्क्रीन सेवर", "डेस्कटॉप कैचर", "मॉनिटर रीडर"], answer: 1, topic: 'OS' },
    { q: "1 MB में कितने किलोबाइट होते हैं?", options: ["1000", "100", "1024", "8"], answer: 2, topic: 'Fundamentals' },
    { q: "MAC का आकार कितना होता है?", options: ["32 बिट्स", "64 बिट्स", "48 बिट्स", "128 बिट्स"], answer: 2, topic: 'Network' },
    { q: "इनमें से कौन-सा क्षेत्र AI के निकटतम है?", options: ["इतिहास", "गणित", "भूगोल", "नागरिक शास्त्र"], answer: 1, topic: 'Future' },
    { q: "बैंक बचत जमा पर ब्याज दिया जाता है?", options: ["मासिक", "अर्धवार्षिक", "त्रैमासिक", "वार्षिक"], answer: 1, topic: 'Banking' },
    { q: "डेजी व्हील प्रिंटर को भी कहते हैं", options: ["लेजर प्रिंटर", "गोल्फ बॉल प्रिंटर", "इंकजेट प्रिंटर", "डॉट मैट्रिक्स"], answer: 1, topic: 'Fundamentals' },
    { q: "निम्न में से कौन एक बैंकिंग उत्पाद है?", options: ["टैक्स", "बचत खाता", "बीमा", "शेयर"], answer: 1, topic: 'Banking' },
    { q: "गूगल की स्थापना किस वर्ष हुई थी?", options: ["1995", "2000", "1998", "2004"], answer: 2, topic: 'Internet' },
    { q: "प्रोसेस्ड डाटा के सेट को कहा जाता है", options: ["डाटा", "इनपुट", "इनफॉर्मेशन", "रॉ फैक्ट्स"], answer: 2, topic: 'Fundamentals' },
    { q: "इनमें से किसका रैम (RAM) में प्रयोग होता है?", options: ["वैक्यूम ट्यूब", "सेमी कंडक्टर", "ट्रांजिस्टर", "मैग्नेटिक टेप"], answer: 1, topic: 'Fundamentals' },
    { q: "सेव के लिए विण्डो शॉर्टकट है", options: ["Ctrl + A", "Alt + S", "Ctrl + S", "Shift + S"], answer: 2, topic: 'Shortcuts' },
    { q: "सॉफ्टवेयर जिसके द्वारा वेबसाइट को देखा जा सकता है", options: ["वेब सर्वर", "इन्टरनेट ब्राउजर", "ऑपरेटिंग सिस्टम", "एंटीवायरस"], answer: 1, topic: 'Internet' },
    { q: "वायरस है", options: ["नेचुरल", "मैन मेड", "मशीन मेड", "ऑटोमेटिक"], answer: 1, topic: 'Security' },
    { q: "कौन-सा प्रोटोकॉल फाइल भेजने के लिए प्रयोग किया जाता है?", options: ["HTTP", "FTP", "SMTP", "TCP"], answer: 1, topic: 'Internet' },
    { q: "MS DOS में एक्सटेंशन के बिना फाइल पहचानने योग्य नहीं है", options: ["असत्य", "सत्य"], answer: 1, topic: 'OS' },
    { q: "भारत के पहले सुपर कम्प्यूटर का क्या नाम है?", options: ["क्र्रे 1", "परम 8000", "आईबीएम", "सिद्धार्थ"], answer: 1, topic: 'Fundamentals' },
    { q: "निम्न में से किस फॉर्मेट में कम्प्यूटर डाटा स्टोर करता है?", options: ["डेसिमल", "बाइनरी", "हेक्साडेसिमल", "ऑक्टल"], answer: 1, topic: 'Fundamentals' },
    { q: "नेटवर्क की भौतिक व्यवस्था क्या कहलाती है?", options: ["प्रोटोकॉल", "टोपोलॉजी", "राउटिंग", "सर्वर"], answer: 1, topic: 'Network' },
    { q: "ऐप के माध्यम से अनारक्षित टिकटिंग सिस्टम (UTS) कब लॉन्च किया गया?", options: ["जनवरी 2018", "जनवरी 2019", "दिसम्बर 2018", "फरवरी 2019"], answer: 1, topic: 'Govt' },
    { q: "टेक्स्ट को राइट एलाइन करने के लिए किसका प्रयोग करते हैं?", options: ["Ctrl + L", "Ctrl + E", "Ctrl + R", "Ctrl + J"], answer: 2, topic: 'Shortcuts' },
   { q: "Gmail में अधिकतम अटैचमेंट साइज कितना होता है?", options: ["20 MB", "25 MB", "15 MB", "10 MB"], answer: 1, topic: 'Email' },
    { q: "LibreOffice Writer में 'Hyperlink' की शॉर्टकट की क्या है?", options: ["Ctrl + H", "Ctrl + L", "Ctrl + K", "Ctrl + M"], answer: 2, topic: 'Writer' },
    { q: "किसी फाइल को Recycle Bin में भेजे बिना स्थायी रूप से डिलीट करने के लिए क्या दबाते हैं?", options: ["Ctrl + Delete", "Alt + Delete", "Shift + Delete", "Delete"], answer: 2, topic: 'OS' },
    { q: "LibreOffice Calc में नंबर डिफॉल्ट रूप से किस एलाइनमेंट (Alignment) में होते हैं?", options: ["Left", "Center", "Right", "Justified"], answer: 2, topic: 'Calc' },
    { q: "पहला नेटवर्क कौन सा था?", options: ["INTERNET", "PAN", "LAN", "ARPANET"], answer: 3, topic: 'Network' },
    { q: "LibreOffice Writer में न्यूनतम जूम (Minimum Zoom) कितना प्रतिशत होता है?", options: ["10%", "5%", "20%", "15%"], answer: 2, topic: 'Writer' },
    { q: "IMAP का उपयोग किसके लिए किया जाता है?", options: ["ईमेल भेजने के लिए", "ईमेल डाउनलोड/प्राप्त करने के लिए", "फाइल अपलोड करने के लिए", "चैट करने के लिए"], answer: 1, topic: 'Email' },
    { q: "LinkedIn मुख्य रूप से किसके लिए उपयोग किया जाता है?", options: ["मनोरंजन", "सोशल नेटवर्किंग", "प्रोफेशनल नेटवर्किंग और नौकरी", "गेमिंग"], answer: 2, topic: 'Social' },
    { q: "LibreOffice में 'Print Preview' की शॉर्टकट की क्या है?", options: ["Ctrl + Shift + O", "Ctrl + F2", "Ctrl + Shift + P", "Ctrl + P"], answer: 0, topic: 'Writer' },
    { q: "UMANG ऐप कितनी भाषाओं का समर्थन करता है?", options: ["10", "12", "13", "15"], answer: 2, topic: 'Govt' },
    { q: "CVV कितने अंकों का होता है?", options: ["4", "3", "5", "6"], answer: 1, topic: 'Banking' },
    { q: "LibreOffice Calc में 'ROUND(175.468, 2)' का मान क्या होगा?", options: ["175.47", "175.46", "175.50", "175.40"], answer: 0, topic: 'Calc' },
    { q: "IP एड्रेस के कितने भाग (Classes) होते हैं?", options: ["4", "3", "5", "6"], answer: 2, topic: 'Network' }, // Classes A, B, C, D, E
    { q: "Linux में नया फोल्डर (Directory) बनाने के लिए किस कमांड का उपयोग होता है?", options: ["md", "mkdir", "cd", "rmdir"], answer: 1, topic: 'OS' },
    { q: "निम्नलिखित में से कौन सी मेमोरी वोलेटाइल (Volatile) है?", options: ["ROM", "Hard Disk", "Pendrive", "RAM"], answer: 3, topic: 'Fundamentals' },
    { q: "WWW का आविष्कार किसने किया था?", options: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Vint Cerf"], answer: 1, topic: 'Internet' },
    { q: "एक निबल (Nibble) कितने बिट्स के बराबर होता है?", options: ["8 Bits", "16 Bits", "4 Bits", "32 Bits"], answer: 2, topic: 'Fundamentals' },
    { q: "LibreOffice Impress में डिफॉल्ट व्यू कौन सा होता है?", options: ["Slide Sorter", "Normal", "Outline", "Notes"], answer: 1, topic: 'Impress' },
    { q: "Check की वैधता (Validity) कितने समय की होती है?", options: ["6 महीने", "1 साल", "3 महीने", "लाइफटाइम"], answer: 2, topic: 'Banking' },
    { q: "NEFT सेवा कब उपलब्ध होती है?", options: ["केवल बैंकिंग घंटों में", "24x7x365", "सुबह 8 से शाम 7", "केवल कार्य दिवसों पर"], answer: 1, topic: 'Payments' },
    { q: "LibreOffice Writer में डिफ़ॉल्ट फ़ाइल का नाम क्या होता है?", options: ["Document1", "Untitled 1", "NewFile", "LibreDoc"], answer: 1, topic: 'Writer' },
    { q: "Facebook पर अकाउंट बनाने के लिए न्यूनतम आयु कितनी होनी चाहिए?", options: ["18 वर्ष", "13 वर्ष", "15 वर्ष", "21 वर्ष"], answer: 1, topic: 'Social' },
    { q: "AI के पिता (Father of AI) किसे माना जाता है?", options: ["Charles Babbage", "Alan Turing", "John McCarthy", "Tim Berners-Lee"], answer: 2, topic: 'Future' },
    { q: "HTTP का डिफॉल्ट पोर्ट नंबर क्या है?", options: ["8080", "21", "25", "80"], answer: 3, topic: 'Internet' },
    { q: "QR कोड का आविष्कार किस कंपनी ने किया था?", options: ["Toyota (Denso Wave)", "Honda", "Microsoft", "Google"], answer: 0, topic: 'Future' },
    { q: "LibreOffice Calc में कुल कितने कॉलम होते हैं?", options: ["1024", "16384", "256", "65536"], answer: 0, topic: 'Calc' },
    { q: "निम्नलिखित में से कौन सा एक सर्च इंजन नहीं है?", options: ["Google", "Bing", "Yahoo", "Windows"], answer: 3, topic: 'Internet' },
    { q: "MAC एड्रेस किस फॉर्मेट में होता है?", options: ["बाइनरी (Binary)", "डेसिमल (Decimal)", "हेक्साडेसिमल (Hexadecimal)", "ऑक्टल (Octal)"], answer: 2, topic: 'Network' },
    { q: "LibreOffice Writer में 'Superscript' की शॉर्टकट की क्या है?", options: ["Ctrl + Shift + P", "Ctrl + Shift + B", "Ctrl + = ", "Ctrl + Shift + +"], answer: 0, topic: 'Writer' },
    { q: "IoT का पूरा नाम क्या है?", options: ["Internet of Technology", "Intranet of Things", "Internet of Things", "Input of Things"], answer: 2, topic: 'Future' },
    { q: "पॉकेट वॉलेट (Pocket Wallet) किस बैंक ने शुरू किया था?", options: ["SBI", "HDFC", "ICICI", "Paytm"], answer: 2, topic: 'Banking' },
    { q: "LibreOffice Calc में #### कब दिखाई देता है?", options: ["जब फॉर्मूला गलत हो", "जब सेल की चौड़ाई डेटा दिखाने के लिए कम हो", "जब डेटा उपलब्ध न हो", "जब वैल्यू 0 हो"], answer: 1, topic: 'Calc' },
    { q: "Linux एक _______ ऑपरेटिंग सिस्टम है।", options: ["Single User", "Open Source", "Paid", "None"], answer: 1, topic: 'OS' },
    { q: "AEPS के लिए किसकी आवश्यकता होती है?", options: ["पासवर्ड", "पिन", "बायोमेट्रिक (फिंगरप्रिंट)", "ओटीपी"], answer: 2, topic: 'Payments' },
    { q: "LibreOffice Impress में स्लाइड ट्रांजिशन क्या है?", options: ["एक ऑब्जेक्ट पर एनीमेशन", "एक स्लाइड से दूसरी स्लाइड पर जाने का विजुअल इफेक्ट", "स्लाइड का डिजाइन", "स्लाइड का लेआउट"], answer: 1, topic: 'Impress' },
    { q: "कंप्यूटर में 'Bug' का क्या अर्थ है?", options: ["वायरस", "सॉफ्टवेयर में गलती (Error)", "एक प्रोग्राम", "हार्डवेयर"], answer: 1, topic: 'Fundamentals' },
    { q: "किसी टेक्स्ट के ऊपर लाइन खींचने को क्या कहते हैं?", options: ["Underline", "Overline", "Strikethrough", "Bold"], answer: 1, topic: 'Writer' } // Note: Strikethrough is through the middle, Overline is above.
];
